spring.application.name=QUOTE-SERVICE

server.port=8084

# =========================
# EUREKA DISABLED
# =========================

eureka.client.enabled=false
spring.cloud.discovery.enabled=false

# =========================
# RESILIENCE4J
# =========================

resilience4j.retry.instances.riskRetry.max-attempts=3
resilience4j.retry.instances.riskRetry.wait-duration=1s

resilience4j.circuitbreaker.instances.riskCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.riskCB.sliding-window-size=5

logging.level.io.github.resilience4j=DEBUG

# =========================
# KAFKA + AVRO
# =========================

#spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.bootstrap-servers=kafka-broker:9092
# Consumer
spring.kafka.consumer.group-id=quote-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

# Schema Registry
spring.kafka.properties.schema.registry.url=http://schema-registry:8081

# Avro
spring.kafka.consumer.properties.specific.avro.reader=true

# =========================
# ACTUATOR
# =========================

management.endpoints.web.exposure.include=*
management.endpoints.enabled-by-default=true
management.endpoint.health.show-details=always
management.endpoint.metrics.access=unrestricted
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true


spring.datasource.url=jdbc:h2:file:/data/quotedb2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console