name: Build Project

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout quote-api
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Give Permission to mvnw
        run: chmod +x mvnw

#      - name: Clone common-avro
#        run: |
#          git clone https://github.com/yManideep2108/common-avro.git

#      - name: Checkout common-avro
#        uses: actions/checkout@v4
#        with:
#          repository: yManideep2108/common-avro
#          path: common-avro
      - name: Checkout common-avro
        uses: actions/checkout@v4
        with:
          repository: yManideep2108/common-avro
          ref: main
          path: common-avro

      - name: Build common-avro
        run: |
          cd common-avro
          chmod +x mvnw
          ./mvnw clean install -DskipTests

      - name: Build quote-api
        run: ./mvnw clean package -DskipTests